#il file yaml non viene caricato automaticamente bisogna dire a ROS2 di usarlo
#lo specifichiamo nel file launch
audio_publisher:
  ros__parameters:
    device_index: 2
    device_name: "Scarlett 18i16 4th Gen"
    #sample_rate: 44100
    sample_rate: 48000
    channels: 4
    chunk_size: 1024
    #chunk_duration: 0.1
    chunk_duration: 0.05
    sample_format: "S16LE"
    coding_format: "PCM"
    # Nuovi parametri base per i topic dinamici
    base_stream_topic: "audio_stream"
    base_info_topic: "audio_info"

audio_subscriber:
  ros__parameters:
    # Parametri operativi
    #sample_rate: 44100
    sample_rate: 48000
    channels: 4

    # Parametri per il salvataggio
    output_directory: "recorded_audio"
    output_base_name: "mic"

    # Parametri per i topic dinamici
    base_stream_topic: "audio_stream"
    base_info_topic: "audio_info"
